version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - inbound


  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - inbound

    links:
      - database_ignite
    depends_on:
      - database_ignite
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    container_name: redis
    networks:
      - inbound

volumes:
  pgdata:
    driver: local

networks:
  inbound:
    driver: bridge